### ISSUE TITLE
There was an error building your app

### ISSUE THREAD

**Issue by peternguyen88** [fabiandev/angular2-quiz-app#10]
I just got this message when running npm install: "There was an error building your app"
No more log. 
P/s: I'm running the latest Node version 6.7

**Comment by fabiandev** [comment]
I just tested cloning the repo and going through the quick start guide with node 6.3 and 6.7 and everything worked fine for me. Did you check that [gulp](https://github.com/gulpjs/gulp), [typings](https://github.com/typings/typings) and [jspm@beta](https://github.com/jspm/jspm-cli) are installed globally?

Are you on Windows or Mac? It's been a while since i tested on Windows.

**Comment by peternguyen88** [comment]
I installed everything is installed. They worked in other projects from github.
And I'm using Window.

**Comment by fabiandev** [comment]
There was actually a Windows related bug in the gulpfile.
I just released a patch version, so please update to 1.1.4 an try again. It should work now.

**Comment by peternguyen88** [comment]
Thanks. It worked now.
